### ISSUE TITLE
Production admin panel prone to `504` gateway timeouts

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-general#30]
These can be solved with a refresh of the page, but can be annoying. Seem to happen relatively regularly.

**Comment by mileswwatkins** [comment]
Ugh, I'm pretty sure this is a `uwsgi` error, but the log isn't very helpful, at least at current verbosity:

```
[pid: 11322|app: 0|req: 95/95] 205.153.36.170 () {44 vars in 734 bytes} [Thu Oct 11 17:51:02 2018] GET /elections18/calls/senate/ => generated 332517 bytes in 1543 msecs (HTTP/1.1 200) 3 headers in 146 bytes (2 switches on core 0)
[pid: 11322|app: 0|req: 96/96] 205.153.36.170 () {44 vars in 734 bytes} [Thu Oct 11 17:51:13 2018] GET /elections18/calls/senate/ => generated 332517 bytes in 1471 msecs (HTTP/1.1 200) 3 headers in 146 bytes (2 switches on core 0)
[pid: 11322|app: 0|req: 97/97] 205.153.36.170 () {44 vars in 734 bytes} [Thu Oct 11 17:51:25 2018] GET /elections18/calls/senate/ => generated 332517 bytes in 1908 msecs (HTTP/1.1 200) 3 headers in 146 bytes (2 switches on core 0)
[pid: 11322|app: 0|req: 98/98] 205.153.36.170 () {50 vars in 936 bytes} [Thu Oct 11 17:51:27 2018] POST /elections18/calls/senate/call-chamber => generated 7 bytes in 20 msecs (HTTP/1.1 200) 3 headers in 141 bytes (1 switches on core 0)
[pid: 11322|app: 0|req: 99/99] 205.153.36.170 () {44 vars in 734 bytes} [Thu Oct 11 17:51:27 2018] GET /elections18/calls/senate/ => generated 51 bytes in 21 msecs (HTTP/1.1 500) 3 headers in 161 bytes (1 switches on core 0)
[pid: 11322|app: 0|req: 100/100] 205.153.36.170 () {44 vars in 734 bytes} [Thu Oct 11 17:51:37 2018] GET /elections18/calls/senate/ => generated 332521 bytes in 1861 msecs (HTTP/1.1 200) 3 headers in 146 bytes (2 switches on core 0)
...The work of process 11322 is done. Seeya!
worker 1 killed successfully (pid: 11322)
Respawned uWSGI worker 1 (new pid: 12114)
[pid: 12114|app: 0|req: 101/101] 205.153.36.170 () {44 vars in 781 bytes} [Thu Oct 11 17:51:47 2018] GET /elections18/calls/senate/ => generated 332521 bytes in 1429 msecs (HTTP/1.1 200) 3 headers in 146 bytes (1 switches on core 0)
[pid: 12114|app: 0|req: 102/102] 205.153.36.170 () {42 vars in 714 bytes} [Thu Oct 11 17:51:49 2018] GET /elections18/less/calls.less => generated 167879 bytes in 1515 msecs (HTTP/1.1 200) 3 headers in 130 bytes (1 switches on core 0)
```

**Comment by mileswwatkins** [comment]
Python app error, from earlier this week:

```
Exception on /elections18/calls/senate/ [GET]
Traceback (most recent call last):
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 61, in calls_admin
    chamber_call_override = results.first().meta.first().chamber_call_override
AttributeError: 'NoneType' object has no attribute 'chamber_call_override'
Exception on /elections18/calls/house/ [GET]
Traceback (most recent call last):
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/apps/elections18_general/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 61, in calls_admin
    chamber_call_override = results.first().meta.first().chamber_call_override
AttributeError: 'NoneType' object has no attribute 'meta'
```

**Comment by mileswwatkins** [comment]
cc https://github.com/nprapps/elections18-general/issues/24

**Comment by mileswwatkins** [comment]
Regardless of database-up-ness, _why_ is a _successful_ page request taking 30 seconds?! There's got to be a more effective, atomic query; I imagine right now there're many round-trips to the database to build a single page, and that's causing a lot of our woes.

**Comment by mileswwatkins** [comment]
But right now, refreshing the page can recover from a `504` with a refresh. And no more errors in the Python log.

**Comment by mileswwatkins** [comment]
<img width="1343" alt="screen shot 2018-10-24 at 16 42 21" src="https://user-images.githubusercontent.com/4959135/47460180-e53a9000-d7ab-11e8-948f-23b18962317c.png">

**Comment by mileswwatkins** [comment]
Profiled, and it does look like the database call is expensive _even locally_:

```
    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
         1    4.314    4.314    4.314    4.314 {method 'read' of '_io.BufferedReader' objects}
```

**Comment by mileswwatkins** [comment]
That refactor drops the time down to about 20% of what it was before locally, going to see how it is in production.

**Comment by mileswwatkins** [comment]
Hell yes

<img width="1248" alt="screen shot 2018-10-25 at 13 17 43" src="https://user-images.githubusercontent.com/4959135/47518240-651e3400-d858-11e8-9dea-7b7c9b262bab.png">

**Comment by mileswwatkins** [comment]
Marking this as mostly finished for now. Haven't seen a `504` since the updated deployment. Occasionally there will be `500`s when the database is empty, which is to be expected.
